apiVersion: v1
kind: Pod
metadata:
  labels:
    app: app1-build-pod

spec:
  serviceAccountName: jenkins

  containers:

  # 🔹 Node container (frontend build)
  - name: node
    image: node:18
    command:
      - cat
    tty: true

  # 🔹 Docker container (image build)
  - name: docker
    image: docker:24-dind
    securityContext:
      privileged: true
    command:
      - dockerd-entrypoint.sh
    tty: true
    volumeMounts:
      - name: docker-sock
        mountPath: /var/run/docker.sock

  # 🔹 Kubectl container (deployment)
  - name: kubectl
    image: bitnami/kubectl:latest
    command:
      - cat
    tty: true

  # 🔹 Workspace volume
  volumes:
    - name: docker-sock
      hostPath:
        path: /run/docker.sock
