apiVersion: v1
kind: Pod
metadata:
  labels:
    app: node_app

spec:
  serviceAccountName: jenkins

  containers:
  # 🔹 Node container (frontend build)
  - name: node
    image: 172.31.42.17:32000/node:18
    command:
      - cat
    tty: true
    workingDir: /home/jenkins/agent

  # 🔹 Docker container (image build)
  - name: docker
    image: 172.31.42.17:32000/docker:24
    securityContext:
      privileged: true
    command:
      - dockerd-entrypoint.sh
    tty: true
    workingDir: /home/jenkins/agent
    volumeMounts:
      - name: docker-sock
        mountPath: /var/run/docker.sock

  # 🔹 Kubectl container (deployment)
  - name: kubectl
    image: 172.31.42.17:32000/kubectl:1
    command:
      - cat
    tty: true
    workingDir: /home/jenkins/agent

  - name: trivy
    image: 172.31.42.17:32000/trivy:0.55.0
    command:
      - cat
    tty: true
    workingDir: /home/jenkins/agent

  - name: zap
    image: 172.31.42.17:32000/zaproxy:stable
    command:
      - cat
    tty: true
    workingDir: /home/jenkins/agent
  

  # 🔹 Volumes (shared workspace + docker socket)
  volumes:
    - name: docker-sock
      hostPath:
        path: /run/docker.sock
