apiVersion: v1
kind: Pod
metadata:
  labels:
    app: node_app

spec:
  serviceAccountName: jenkins
  imagePullSecrets:
    - name: nexus-secret

  containers:

  # 🔹 Node container
  - name: node
    image: 172.31.42.17:32000/node:18
    command: ['cat']
    tty: true
    workingDir: /home/jenkins/agent

  # 🔹 Docker CLI container
  - name: docker
    image: 172.31.42.17:32000/docker:24
    command: ['cat']
    tty: true
    workingDir: /home/jenkins/agent
    volumeMounts:
      - name: docker-sock
        mountPath: /var/run/docker.sock

  # 🔹 Kubectl container
  - name: kubectl
    image: 172.31.42.17:32000/kubectl:1
    command: ['cat']
    tty: true
    workingDir: /home/jenkins/agent

  # 🔹 Trivy container
  - name: trivy
    image: 172.31.42.17:32000/trivy:0.55.0
    command: ['cat']
    tty: true
    workingDir: /home/jenkins/agent

  # 🔹 ZAP container
  - name: zap
    image: 172.31.42.17:32000/zaproxy:stable
    command: ['cat']
    tty: true
    workingDir: /home/jenkins/agent

  # 🔹 Volumes (MUST be outside containers)
  volumes:
    - name: docker-sock
      hostPath:
        path: /run/docker.sock
